//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGameOfLife
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class UserGame
    {
        public int UserGameID { get; set; }

        [HiddenInput(DisplayValue = false)]
        [DefaultValue(2)]
        public int UserID { get; set; }

        [Required]
        public string Name { get; set; }

        [Required]
        [Range(1, 60,
            ErrorMessage = "Width must be between 1 and 60")]
        public int Height { get; set; }

        [Required]
        [Range(1, 60,
            ErrorMessage = "Width must be between 1 and 60")]
        public int Width { get; set; }

        [Required]
        public string Cells { get; set; }

        public virtual User User { get; set; }
    }
}