//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebGameOfLife
{
    using Attributes;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserTemplate
    {
        public int UserTemplateID { get; set; }
        public int UserID { get; set; }
        public string Name { get; set; }
        [Range(1, 10,
            ErrorMessage = "Height must be between 1 and 10")]
        public int Height { get; set; }
        [Range(1, 10,
            ErrorMessage = "Width must be between 1 and 10")]
        public int Width { get; set; }
        [CellsLength(ErrorMessage = "Cells length must be the same as the product of Height * Width")]
        [CellsChars(ErrorMessage = "Must only contain the letter 'X' or 'O'")]
        [Required]
        public string Cells { get; set; }

        public virtual User User { get; set; }
    }
}